// ==UserScript==
// @name        POUCAVE
// @author      Snizzle
// @version     2.1
// @downloadURL https://github.com/Snizzle-jvc/Poucave/raw/master/Poucave.user.js
// @updateURL   https://github.com/Snizzle-jvc/Poucave/raw/master/Poucave.user.js
// @supportURL  http://www.jeuxvideo.com/messages-prives/nouveau.php?all_dest=Snizzle,Snitchzzle
// @copyright   2018, Snizzle
// @licence     MIT
// @description Poucave à la modé n'a jamais été aussi simple
// @grant       none
// @require     https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js
// @match       *://www.jeuxvideo.com/forums/*
// @run-at      document-end
// ==/UserScript==
$(function(a){a(".group-one").prepend("<div class='btn btn-actu-new-list-forum' id='poucave-save-topic' title='Enregistrer ce topic' style='margin-right: 10px; background-color: #3a83a9; border-color: #2e6e90;border-radius: 0; color: white' >enregistrer</div>");a(".group-one").prepend("<div class='btn btn-actu-new-list-forum' id='poucave-send-topic' title='Poucaaaave' style='margin-right: 10px; background-color: red; border-color: #c70b0b;border-radius: 0; color: white' >poucave</div>");a(".bloc-date-msg a").html("Enregistrer ce message!");
a(".col-right").prepend("<div class='panel panel-jv-forum panel-poucave' style='background:none'><div class='panel-body'><div class='scrollable'><div class='scrollable-wrapper'><div class='scrollable-content bloc-sous-forums'><ul class='liste-sous-forums'><li class='line-ellipsis'><div class='btn btn-actu-new-list-forum' id='poucave-mod' title='Topic de mod\u00e9ration choisi' style='background-color: #696969;border-color: #696969;border-radius: 0;color: white;min-width: 9rem;'>Topic de mod\u00e9ration</div></li><li class='line-ellipsis'><div class='btn btn-actu-new-list-forum' id='poucave-clear' title='Vider la liste de signalements' style='background-color: #696969;border-color: #696969;border-radius: 0;color: white;min-width: 13rem;'>Vider la liste de signalements</div></li></ul></div></div></div></div></div>");
var e=window.location.href,g=JSON.parse(localStorage.getItem("Topic"))||[],h=JSON.parse(localStorage.getItem("Message"))||[],f=localStorage.getItem("Alias"),b=localStorage.getItem("Moderation");null===f&&(f="");if(null===b||0==b)b="",alert("Vous n'avez pas sp\u00e9cifi\u00e9 de topic de Mod\u00e9ration");null!==localStorage.getItem("Topic")&&localStorage.getItem("Topic").includes(e)&&a("#poucave-save-topic").hide();a("#poucave-clear").click(function(){if(null!==localStorage.getItem("Topic")||null!==
localStorage.getItem("Message"))1==confirm("Vider la liste de signalements ?")&&(localStorage.removeItem("Topic"),localStorage.removeItem("Message"));else return alert("Liste d\u00e9j\u00e0 vide")});a("#poucave-save-topic").click(function(){var c=prompt("Raison du signalement",""),d="'''"+c+"'''";""===c&&(d="");null===c?alert("Le topic n'a pas \u00e9t\u00e9 enregistr\u00e9!"):(c="[TOPIC] "+d+" : ",(JSON.parse(localStorage.getItem("Topic"))||[]).push(c+e+"\n"),a(this).hide())});a(".bloc-date-msg a").click(function(c){c.preventDefault();
c="http://www.jeuxvideo.com"+a(this).attr("href");if(null!==localStorage.getItem("Message")&&localStorage.getItem("Message").includes(c))return a(this).hide(),alert("Message d\u00e9j\u00e0 signal\u00e9");var d=prompt("Raison du signalement",""),b="'''"+d+"'''";""===d&&(b="");null===d?alert("Le message n'a pas \u00e9t\u00e9 enregistr\u00e9!"):(d="[MSG] "+b+" : ",b=JSON.parse(localStorage.getItem("Message"))||[],b.push(d+c+"\n"),localStorage.setItem("Message",JSON.stringify(b)),a(this).hide())});a("#poucave-mod").click(function(){var c=
prompt("Collez le lien du topic de mod\u00e9ration",b);if(null!==c&&""!==c){var a=prompt("Donnez un nom \u00e0 ce forum (par exemple : 18-25)");if(null===a||0==a)a="";localStorage.setItem("Moderation",c);localStorage.setItem("Alias",a);location.reload()}});a("#poucave-mod").html("Topic de mod\u00e9 : "+f);a("#poucave-send-topic").click(function(){if(null===b||0==b)return alert("Vous n'avez pas sp\u00e9cifi\u00e9 de topic de Mod\u00e9ration");var a=JSON.parse(localStorage.getItem("Topic"))||[],d=JSON.parse(localStorage.getItem("Message"))||
[];a=a.join("")+d.join("");""===a?alert("Rien \u00e0 poucave !"):1==confirm("Veux-tu poucave maintenant ?\n"+a)&&window.open(b+"#pouc").focus()});e===b+"#pouc"&&(a("#message_topic").focus().text(g.join("")+h.join("")),localStorage.removeItem("Topic"),localStorage.removeItem("Message"))});
